CREATE TABLE [dbo].[Food]
(
[Id] INT IDENTITY(1,1) NOT NULL,
[Name] NCHAR(100) NOT NULL,
[Kcal] DECIMAL(10,2) NULL,
[Carbs] DECIMAL(10,2) NULL,
[Protein] DECIMAL(10,2) NULL,
[Fats] DECIMAL(10,2) NULL,
CONSTRAINT PK_Food_Id PRIMARY KEY (Id),
)